# Generated by Django 4.2.14 on 2024-08-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default=0, max_length=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad Economica',
                'verbose_name_plural': 'Actividades Economicas',
                'db_table': 'backend.actividad_economica',
            },
        ),
        migrations.CreateModel(
            name='ActividadPrincipalCNAE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Actividad CNAE',
                'db_table': 'backend.actividad_principal_cnae',
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Denominacion',
                'db_table': 'backend.denominacion',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Origenes',
                'db_table': 'backend.origen',
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Sector Economico',
                'verbose_name_plural': 'Sectores Economicos',
                'db_table': 'backend.sector_economico',
            },
        ),
        migrations.CreateModel(
            name='TipoMypime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Mypime',
                'verbose_name_plural': 'Tipos Mypimes',
                'db_table': 'backend.tipo_mipyme',
            },
        ),
        migrations.CreateModel(
            name='TipoSujeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo Sujeto',
                'verbose_name_plural': 'Tipos Sujetos',
                'db_table': 'backend.tipo_sujeto',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('segundo_nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('carnet', models.CharField(max_length=11)),
                ('fecha_nacimiento', models.DateField(default=None)),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('tomo', models.CharField(max_length=3)),
                ('folio', models.CharField(max_length=3)),
                ('tipo_mipyme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_mipyme_en_posecion', to='api.tipomypime')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'backend.solicitante',
            },
        ),
        migrations.CreateModel(
            name='ActorEconomico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('solicitud', models.CharField(max_length=11)),
                ('telefonos', models.CharField(max_length=8)),
                ('correo_representante', models.EmailField(max_length=254)),
                ('domicilio_social', models.CharField(max_length=250)),
                ('cantidad_socios', models.IntegerField()),
                ('cantidad_trabajadores', models.IntegerField()),
                ('cantidad_estatales', models.IntegerField()),
                ('cantidad_TPCP', models.IntegerField()),
                ('cantidad_CNA', models.IntegerField()),
                ('cantidad_desempleados', models.IntegerField()),
                ('cantidad_otros_origenes', models.IntegerField()),
                ('cantidad_ocupados', models.IntegerField()),
                ('pdl', models.CharField(max_length=100)),
                ('inscrito_registro_mercantil', models.BooleanField()),
                ('tomo_inscripcion', models.CharField(blank=True, max_length=10)),
                ('folio_inscripcion', models.CharField(blank=True, max_length=10)),
                ('hoja_inscripcion', models.CharField(blank=True, max_length=10)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, null=True)),
                ('is_exportador', models.BooleanField(default=False)),
                ('is_incubado_en_parque_cientifico', models.BooleanField(default=False)),
                ('desistimiento_con_carta_de_socios', models.BooleanField(default=False)),
                ('is_disuelta', models.BooleanField(default=False)),
                ('is_inactiva', models.BooleanField(default=False)),
                ('actividad_economica_principal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actividadeconomica')),
                ('actividad_principal_CNAE_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_principal_CNAE', to='api.actividadprincipalcnae')),
                ('denominacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.denominacion')),
                ('origen_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='api.origen')),
                ('sector_economico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_economico', to='api.sectoreconomico')),
                ('solicitante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitante')),
                ('tipo_mypime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_mipyme', to='api.tipomypime')),
                ('tipo_sujeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tiposujeto')),
            ],
            options={
                'verbose_name': 'Actor Economico',
                'verbose_name_plural': 'Actores Economicos',
                'db_table': 'backend.actores_economicos',
            },
        ),
    ]
