# Generated by Django 5.1.2 on 2024-11-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actoreconomico',
            old_name='telefonos',
            new_name='telefono',
        ),
    ]
