# Generated by Django 5.1.2 on 2024-11-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_telefonos_actoreconomico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actoreconomico',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
