# Generated by Django 5.1.2 on 2024-11-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_actoreconomico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='codigo',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
