# Generated by Django 5.1.2 on 2024-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_actividadeconomica_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
