# Generated by Django 5.1.2 on 2024-11-06 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_solicitante_segundo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoreconomico',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
